apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: sample-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: docker.io/sukhilsuresh/sample-operator-bundle-index:1.0.0
  displayName: Sample
  publisher: sukhil-suresh
  updateStrategy:
    registryPoll:
      interval: 1h
